// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SaudeFit.Infrastructure.Data;

#nullable disable

namespace SaudeFit.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251111205205_AddAlimentos")]
    partial class AddAlimentos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SaudeFit.Domain.Entities.Alimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Calorias")
                        .HasColumnType("int");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Refeicao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Alimentos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Calorias = 300,
                            Categoria = "Abaixo do peso",
                            Descricao = "Fonte de energia e fibras para ganho de peso saudável",
                            Nome = "Vitamina de banana com aveia",
                            Refeicao = "Café da manhã"
                        },
                        new
                        {
                            Id = 2,
                            Calorias = 600,
                            Categoria = "Abaixo do peso",
                            Descricao = "Refeição completa e rica em proteínas e carboidratos",
                            Nome = "Arroz, feijão e frango grelhado",
                            Refeicao = "Almoço"
                        },
                        new
                        {
                            Id = 3,
                            Calorias = 350,
                            Categoria = "Abaixo do peso",
                            Descricao = "Boa combinação de gorduras boas e proteínas",
                            Nome = "Pão integral com pasta de amendoim",
                            Refeicao = "Lanche da tarde"
                        },
                        new
                        {
                            Id = 4,
                            Calorias = 400,
                            Categoria = "Abaixo do peso",
                            Descricao = "Refeição leve, rica em proteínas e nutrientes",
                            Nome = "Omelete com legumes e arroz",
                            Refeicao = "Jantar"
                        },
                        new
                        {
                            Id = 5,
                            Calorias = 250,
                            Categoria = "Peso normal",
                            Descricao = "Mantém o equilíbrio entre proteínas e fibras",
                            Nome = "Iogurte natural com frutas",
                            Refeicao = "Café da manhã"
                        },
                        new
                        {
                            Id = 6,
                            Calorias = 500,
                            Categoria = "Peso normal",
                            Descricao = "Refeição equilibrada para manutenção do peso",
                            Nome = "Peito de frango com legumes e arroz integral",
                            Refeicao = "Almoço"
                        },
                        new
                        {
                            Id = 7,
                            Calorias = 200,
                            Categoria = "Peso normal",
                            Descricao = "Fonte de gorduras boas e energia natural",
                            Nome = "Mix de castanhas e frutas secas",
                            Refeicao = "Lanche da tarde"
                        },
                        new
                        {
                            Id = 8,
                            Calorias = 300,
                            Categoria = "Peso normal",
                            Descricao = "Refeição leve e nutritiva para o fim do dia",
                            Nome = "Sopa de legumes com carne magra",
                            Refeicao = "Jantar"
                        },
                        new
                        {
                            Id = 9,
                            Calorias = 220,
                            Categoria = "Sobrepeso",
                            Descricao = "Baixo teor de gordura e boa fonte de proteína",
                            Nome = "Tapioca com ovo mexido",
                            Refeicao = "Café da manhã"
                        },
                        new
                        {
                            Id = 10,
                            Calorias = 400,
                            Categoria = "Sobrepeso",
                            Descricao = "Refeição balanceada e rica em ômega 3",
                            Nome = "Peixe grelhado com salada e arroz integral",
                            Refeicao = "Almoço"
                        },
                        new
                        {
                            Id = 11,
                            Calorias = 150,
                            Categoria = "Sobrepeso",
                            Descricao = "Opção leve com fibras e proteínas",
                            Nome = "Iogurte light com chia",
                            Refeicao = "Lanche da tarde"
                        },
                        new
                        {
                            Id = 12,
                            Calorias = 280,
                            Categoria = "Sobrepeso",
                            Descricao = "Refeição rica em nutrientes e de baixa caloria",
                            Nome = "Frango desfiado com legumes refogados",
                            Refeicao = "Jantar"
                        },
                        new
                        {
                            Id = 13,
                            Calorias = 180,
                            Categoria = "Obesidade",
                            Descricao = "Mistura de frutas, couve e linhaça para desintoxicação",
                            Nome = "Smoothie verde",
                            Refeicao = "Café da manhã"
                        },
                        new
                        {
                            Id = 14,
                            Calorias = 300,
                            Categoria = "Obesidade",
                            Descricao = "Baixo teor calórico e rico em nutrientes",
                            Nome = "Filé de peixe com legumes no vapor",
                            Refeicao = "Almoço"
                        },
                        new
                        {
                            Id = 15,
                            Calorias = 160,
                            Categoria = "Obesidade",
                            Descricao = "Fonte leve de energia e fibras naturais",
                            Nome = "Salada de frutas com aveia",
                            Refeicao = "Lanche da tarde"
                        },
                        new
                        {
                            Id = 16,
                            Calorias = 220,
                            Categoria = "Obesidade",
                            Descricao = "Jantar leve, nutritivo e de fácil digestão",
                            Nome = "Sopa de abóbora com frango desfiado",
                            Refeicao = "Jantar"
                        });
                });

            modelBuilder.Entity("SaudeFit.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("SaudeFit.Domain.Entities.Exercicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DuracaoMinutos")
                        .HasColumnType("int");

                    b.Property<string>("NivelDificuldade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Repeticoes")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Exercicios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Categoria = "Abaixo do peso",
                            Descricao = "Caminhada de 20 minutos para ganho de resistência",
                            DuracaoMinutos = 20,
                            NivelDificuldade = "Leve",
                            Nome = "Caminhada leve",
                            Repeticoes = 1
                        },
                        new
                        {
                            Id = 2,
                            Categoria = "Abaixo do peso",
                            Descricao = "Série de alongamentos diários",
                            DuracaoMinutos = 15,
                            NivelDificuldade = "Leve",
                            Nome = "Alongamento completo",
                            Repeticoes = 1
                        },
                        new
                        {
                            Id = 9,
                            Categoria = "Abaixo do peso",
                            Descricao = "Exercícios focados em alinhamento corporal e equilíbrio",
                            DuracaoMinutos = 10,
                            NivelDificuldade = "Leve",
                            Nome = "Treino de postura",
                            Repeticoes = 2
                        },
                        new
                        {
                            Id = 10,
                            Categoria = "Abaixo do peso",
                            Descricao = "Sequência leve para fortalecimento e relaxamento",
                            DuracaoMinutos = 25,
                            NivelDificuldade = "Leve",
                            Nome = "Yoga básica",
                            Repeticoes = 1
                        },
                        new
                        {
                            Id = 3,
                            Categoria = "Peso normal",
                            Descricao = "Corrida de 30 minutos",
                            DuracaoMinutos = 30,
                            NivelDificuldade = "Moderado",
                            Nome = "Corrida leve",
                            Repeticoes = 1
                        },
                        new
                        {
                            Id = 4,
                            Categoria = "Peso normal",
                            Descricao = "Série com agachamento, prancha e flexão",
                            DuracaoMinutos = 25,
                            NivelDificuldade = "Moderado",
                            Nome = "Treino funcional",
                            Repeticoes = 3
                        },
                        new
                        {
                            Id = 11,
                            Categoria = "Peso normal",
                            Descricao = "Sequência de polichinelos, corrida no lugar e prancha curta",
                            DuracaoMinutos = 20,
                            NivelDificuldade = "Moderado",
                            Nome = "Circuito aeróbico",
                            Repeticoes = 2
                        },
                        new
                        {
                            Id = 12,
                            Categoria = "Peso normal",
                            Descricao = "Série alternada com elásticos e abdominais",
                            DuracaoMinutos = 30,
                            NivelDificuldade = "Moderado",
                            Nome = "Treino de resistência",
                            Repeticoes = 3
                        },
                        new
                        {
                            Id = 5,
                            Categoria = "Sobrepeso",
                            Descricao = "Cardio leve para queima de gordura",
                            DuracaoMinutos = 25,
                            NivelDificuldade = "Moderado",
                            Nome = "Bicicleta ergométrica",
                            Repeticoes = 1
                        },
                        new
                        {
                            Id = 6,
                            Categoria = "Sobrepeso",
                            Descricao = "Exercício controlado para pernas",
                            DuracaoMinutos = 15,
                            NivelDificuldade = "Moderado",
                            Nome = "Agachamento com apoio",
                            Repeticoes = 2
                        },
                        new
                        {
                            Id = 13,
                            Categoria = "Sobrepeso",
                            Descricao = "Exercício de esteira com leve inclinação para resistência",
                            DuracaoMinutos = 20,
                            NivelDificuldade = "Moderado",
                            Nome = "Caminhada inclinada",
                            Repeticoes = 1
                        },
                        new
                        {
                            Id = 14,
                            Categoria = "Sobrepeso",
                            Descricao = "Série para tonificar braços e costas",
                            DuracaoMinutos = 15,
                            NivelDificuldade = "Moderado",
                            Nome = "Treino leve com elástico",
                            Repeticoes = 2
                        },
                        new
                        {
                            Id = 7,
                            Categoria = "Obesidade",
                            Descricao = "Exercício de baixo impacto",
                            DuracaoMinutos = 20,
                            NivelDificuldade = "Leve",
                            Nome = "Caminhada aquática",
                            Repeticoes = 1
                        },
                        new
                        {
                            Id = 8,
                            Categoria = "Obesidade",
                            Descricao = "Série para melhorar a capacidade pulmonar",
                            DuracaoMinutos = 10,
                            NivelDificuldade = "Leve",
                            Nome = "Exercícios respiratórios",
                            Repeticoes = 1
                        },
                        new
                        {
                            Id = 15,
                            Categoria = "Obesidade",
                            Descricao = "Movimentos na água para estimular a circulação",
                            DuracaoMinutos = 25,
                            NivelDificuldade = "Leve",
                            Nome = "Hidroginástica leve",
                            Repeticoes = 1
                        },
                        new
                        {
                            Id = 16,
                            Categoria = "Obesidade",
                            Descricao = "Série simples para aumentar a mobilidade",
                            DuracaoMinutos = 15,
                            NivelDificuldade = "Leve",
                            Nome = "Alongamento sentado",
                            Repeticoes = 1
                        });
                });

            modelBuilder.Entity("SaudeFit.Domain.Entities.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Altura")
                        .HasColumnType("float");

                    b.Property<string>("Classificacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Idade")
                        .HasColumnType("int");

                    b.Property<double>("Imc")
                        .HasColumnType("float");

                    b.Property<double>("Peso")
                        .HasColumnType("float");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SaudeFit.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SaudeFit.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SaudeFit.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SaudeFit.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
