// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SaudeFit.Infrastructure.Data;

#nullable disable

namespace SaudeFit.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SaudeFit.Domain.Entities.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DifficultyLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Repetitions")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Abaixo do peso",
                            Description = "Caminhada de 20 minutos para ganho de resistência",
                            DifficultyLevel = "Leve",
                            DurationMinutes = 20,
                            Name = "Caminhada leve",
                            Repetitions = 1
                        },
                        new
                        {
                            Id = 2,
                            Category = "Abaixo do peso",
                            Description = "Série de alongamentos diários",
                            DifficultyLevel = "Leve",
                            DurationMinutes = 15,
                            Name = "Alongamento completo",
                            Repetitions = 1
                        },
                        new
                        {
                            Id = 9,
                            Category = "Abaixo do peso",
                            Description = "Exercícios focados em alinhamento corporal e equilíbrio",
                            DifficultyLevel = "Leve",
                            DurationMinutes = 10,
                            Name = "Treino de postura",
                            Repetitions = 2
                        },
                        new
                        {
                            Id = 10,
                            Category = "Abaixo do peso",
                            Description = "Sequência leve para fortalecimento e relaxamento",
                            DifficultyLevel = "Leve",
                            DurationMinutes = 25,
                            Name = "Yoga básica",
                            Repetitions = 1
                        },
                        new
                        {
                            Id = 3,
                            Category = "Peso normal",
                            Description = "Corrida de 30 minutos",
                            DifficultyLevel = "Moderado",
                            DurationMinutes = 30,
                            Name = "Corrida leve",
                            Repetitions = 1
                        },
                        new
                        {
                            Id = 4,
                            Category = "Peso normal",
                            Description = "Série com agachamento, prancha e flexão",
                            DifficultyLevel = "Moderado",
                            DurationMinutes = 25,
                            Name = "Treino funcional",
                            Repetitions = 3
                        },
                        new
                        {
                            Id = 11,
                            Category = "Peso normal",
                            Description = "Sequência de polichinelos, corrida no lugar e prancha curta",
                            DifficultyLevel = "Moderado",
                            DurationMinutes = 20,
                            Name = "Circuito aeróbico",
                            Repetitions = 2
                        },
                        new
                        {
                            Id = 12,
                            Category = "Peso normal",
                            Description = "Série alternada com elásticos e abdominais",
                            DifficultyLevel = "Moderado",
                            DurationMinutes = 30,
                            Name = "Treino de resistência",
                            Repetitions = 3
                        },
                        new
                        {
                            Id = 5,
                            Category = "Sobrepeso",
                            Description = "Cardio leve para queima de gordura",
                            DifficultyLevel = "Moderado",
                            DurationMinutes = 25,
                            Name = "Bicicleta ergométrica",
                            Repetitions = 1
                        },
                        new
                        {
                            Id = 6,
                            Category = "Sobrepeso",
                            Description = "Exercício controlado para pernas",
                            DifficultyLevel = "Moderado",
                            DurationMinutes = 15,
                            Name = "Agachamento com apoio",
                            Repetitions = 2
                        },
                        new
                        {
                            Id = 13,
                            Category = "Sobrepeso",
                            Description = "Exercício de esteira com leve inclinação para resistência",
                            DifficultyLevel = "Moderado",
                            DurationMinutes = 20,
                            Name = "Caminhada inclinada",
                            Repetitions = 1
                        },
                        new
                        {
                            Id = 14,
                            Category = "Sobrepeso",
                            Description = "Série para tonificar braços e costas",
                            DifficultyLevel = "Moderado",
                            DurationMinutes = 15,
                            Name = "Treino leve com elástico",
                            Repetitions = 2
                        },
                        new
                        {
                            Id = 7,
                            Category = "Obesidade",
                            Description = "Exercício de baixo impacto",
                            DifficultyLevel = "Leve",
                            DurationMinutes = 20,
                            Name = "Caminhada aquática",
                            Repetitions = 1
                        },
                        new
                        {
                            Id = 8,
                            Category = "Obesidade",
                            Description = "Série para melhorar a capacidade pulmonar",
                            DifficultyLevel = "Leve",
                            DurationMinutes = 10,
                            Name = "Exercícios respiratórios",
                            Repetitions = 1
                        },
                        new
                        {
                            Id = 15,
                            Category = "Obesidade",
                            Description = "Movimentos na água para estimular a circulação",
                            DifficultyLevel = "Leve",
                            DurationMinutes = 25,
                            Name = "Hidroginástica leve",
                            Repetitions = 1
                        },
                        new
                        {
                            Id = 16,
                            Category = "Obesidade",
                            Description = "Série simples para aumentar a mobilidade",
                            DifficultyLevel = "Leve",
                            DurationMinutes = 15,
                            Name = "Alongamento sentado",
                            Repetitions = 1
                        });
                });

            modelBuilder.Entity("SaudeFit.Domain.Entities.Food", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Calories")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Snack")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Foods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Calories = 300,
                            Category = "Abaixo do peso",
                            Description = "Fonte de energia e fibras para ganho de peso saudável",
                            Name = "Vitamina de banana com aveia",
                            Snack = "Café da manhã"
                        },
                        new
                        {
                            Id = 2,
                            Calories = 600,
                            Category = "Abaixo do peso",
                            Description = "Refeição completa e rica em proteínas e carboidratos",
                            Name = "Arroz, feijão e frango grelhado",
                            Snack = "Almoço"
                        },
                        new
                        {
                            Id = 3,
                            Calories = 350,
                            Category = "Abaixo do peso",
                            Description = "Boa combinação de gorduras boas e proteínas",
                            Name = "Pão integral com pasta de amendoim",
                            Snack = "Lanche da tarde"
                        },
                        new
                        {
                            Id = 4,
                            Calories = 400,
                            Category = "Abaixo do peso",
                            Description = "Refeição leve, rica em proteínas e nutrientes",
                            Name = "Omelete com legumes e arroz",
                            Snack = "Jantar"
                        },
                        new
                        {
                            Id = 5,
                            Calories = 250,
                            Category = "Peso normal",
                            Description = "Mantém o equilíbrio entre proteínas e fibras",
                            Name = "Iogurte natural com frutas",
                            Snack = "Café da manhã"
                        },
                        new
                        {
                            Id = 6,
                            Calories = 500,
                            Category = "Peso normal",
                            Description = "Refeição equilibrada para manutenção do peso",
                            Name = "Peito de frango com legumes e arroz integral",
                            Snack = "Almoço"
                        },
                        new
                        {
                            Id = 7,
                            Calories = 200,
                            Category = "Peso normal",
                            Description = "Fonte de gorduras boas e energia natural",
                            Name = "Mix de castanhas e frutas secas",
                            Snack = "Lanche da tarde"
                        },
                        new
                        {
                            Id = 8,
                            Calories = 300,
                            Category = "Peso normal",
                            Description = "Refeição leve e nutritiva para o fim do dia",
                            Name = "Sopa de legumes com carne magra",
                            Snack = "Jantar"
                        },
                        new
                        {
                            Id = 9,
                            Calories = 220,
                            Category = "Sobrepeso",
                            Description = "Baixo teor de gordura e boa fonte de proteína",
                            Name = "Tapioca com ovo mexido",
                            Snack = "Café da manhã"
                        },
                        new
                        {
                            Id = 10,
                            Calories = 400,
                            Category = "Sobrepeso",
                            Description = "Refeição balanceada e rica em ômega 3",
                            Name = "Peixe grelhado com salada e arroz integral",
                            Snack = "Almoço"
                        },
                        new
                        {
                            Id = 11,
                            Calories = 150,
                            Category = "Sobrepeso",
                            Description = "Opção leve com fibras e proteínas",
                            Name = "Iogurte light com chia",
                            Snack = "Lanche da tarde"
                        },
                        new
                        {
                            Id = 12,
                            Calories = 280,
                            Category = "Sobrepeso",
                            Description = "Refeição rica em nutrientes e de baixa caloria",
                            Name = "Frango desfiado com legumes refogados",
                            Snack = "Jantar"
                        },
                        new
                        {
                            Id = 13,
                            Calories = 180,
                            Category = "Obesidade",
                            Description = "Mistura de frutas, couve e linhaça para desintoxicação",
                            Name = "Smoothie verde",
                            Snack = "Café da manhã"
                        },
                        new
                        {
                            Id = 14,
                            Calories = 300,
                            Category = "Obesidade",
                            Description = "Baixo teor calórico e rico em nutrientes",
                            Name = "Filé de peixe com legumes no vapor",
                            Snack = "Almoço"
                        },
                        new
                        {
                            Id = 15,
                            Calories = 160,
                            Category = "Obesidade",
                            Description = "Fonte leve de energia e fibras naturais",
                            Name = "Salada de frutas com aveia",
                            Snack = "Lanche da tarde"
                        },
                        new
                        {
                            Id = 16,
                            Calories = 220,
                            Category = "Obesidade",
                            Description = "Jantar leve, nutritivo e de fácil digestão",
                            Name = "Sopa de abóbora com frango desfiado",
                            Snack = "Jantar"
                        });
                });

            modelBuilder.Entity("SaudeFit.Domain.Entities.UserProfile", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<double>("Bmi")
                        .HasColumnType("float");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("UserId");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("SaudeFit.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SaudeFit.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SaudeFit.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SaudeFit.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SaudeFit.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
